# Generated by Django 5.0.4 on 2024-04-16 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_client_ingredient_menu_price_alter_pizza_name_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
