# Generated by Django 5.0.4 on 2024-04-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.FloatField(default=1),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
